service: amazon-scraper

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, 'dev'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

plugins:
  - serverless-offline

functions:
  scraper:
    handler: src/services/productsScraper.getProducts
    events:
      - http:
          path: bestsellers
          method: GET
          cors: true
      - http:
          path: bestsellers/{category}
          method: GET
          cors: true
  listProducts:
    handler: src/utils/dynamoDB.listProducts
    events:
      - http:
          path: products
          method: GET
          cors: true

resources:
  Resources:
    ScraperTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST